### ISSUE TITLE
incompatible with `visual-line-mode`

### ISSUE THREAD

**Issue by llcc** [bastibe/annotate.el#2] opened 2015-06-15 01:39 UTC
Hi @bastibe,

This package looks very promising, but it conflicts with `visual-line-mode`. The reason I think the annotation needs some space in several right columns.

Is there any better choice to adjust the place to other?

**Comment by bastibe** [comment] 2015-06-15 08:10
I just tried running annotate-mode with visual-line-mode, and there don't seem to be any problems.

Could you describe the issue you are seeing in more detail?

**Comment by llcc** [comment] 2015-06-15 08:16
@bastibe `Wrong type argument: wholenump, -954` error message.

**Comment by bastibe** [comment] 2015-06-15 14:40
I'm not getting that error. Therefore, the problem is probably caused by an interaction with some other mode. What other modes are you running?

**Comment by llcc** [comment] 2015-06-15 14:49
This is my minor-mode list enabled in my document mode:
![image](https://cloud.githubusercontent.com/assets/3996879/8162569/2807cb7e-13b9-11e5-8758-1ca2113ffc07.png)

**Comment by bastibe** [comment] 2015-06-15 15:02
I don't see any obvious culprit, there.

Could you try combinations of these on your machine? I don't have all of them installed. 

Here's the modes I run:

Annotate Auto-Composition Auto-Compression Auto-Encryption Blink-Cursor Column-Number Desktop-Save Diff-Auto-Refine Electric-Indent Evil Evil-Local File-Name-Shadow Font-Lock Git-Gutter Global-Auto-Revert Global-Font-Lock Global-Git-Gutter Global-Undo-Tree Ido-Vertical Line-Number Magit-Auto-Revert Menu-Bar Mouse-Wheel Savehist Shell-Dirtrack Tooltip Transient-Mark Undo-Tree Visual-Line Wrap-Region Wrap-Region-Global

**Comment by llcc** [comment] 2015-06-15 15:48
@bastibe Maybe its not a mode conflict issue and not a `visual-line-mode` issue, either.
I did some trials:
1. turned on `visual-line-mode` with lines wrapped, annotation worked well, even i created a super long annotation. 
![image](https://cloud.githubusercontent.com/assets/3996879/8164046/aede1600-13c1-11e5-9f53-920889a58474.png)
But once I delete the end symbol of this line, the annotation disappeared but underline still there.
![image](https://cloud.githubusercontent.com/assets/3996879/8164073/cce1c3b8-13c1-11e5-9dc0-abc1ca71b315.png)
2. `visual-line-mode` still on, but combined the lines together, then the error message took place.
so there must be some problem related to variable `fill-column` in my thought.

**Comment by bastibe** [comment] 2015-06-15 16:27
Yes, currently the annotation is a text property of the last character on the line. If you delete the last character, you will delete the annotation as well. I am working on a solution for this, but I have not found a perfect solution yet.

The error you are seeing is indeed related to fill-column. I can now recreate it. It happens when you create an annotation on a line that is longer than `annotate-annotation-column`. This should be easily fixable.

**Comment by bastibe** [comment] 2015-06-15 16:38
OK, the error should be fixed now. Marmalade has the latest version, and Melpa and Melpa stable should update, soon.

**Comment by llcc** [comment] 2015-06-27 10:15
Same bugs when I try to annotate the source blocks in org-mode!

**Comment by bastibe** [comment] 2015-06-30 11:13
Ok, I'll have a look again.

**Comment by bastibe** [comment] 2015-07-02 08:29
I don't seem to be able to add annotations to org-mode source blocks at all. Is this what you are seeing as well?

**Comment by llcc** [comment] 2015-07-04 10:03
Yes, @bastibe. It is!

**Comment by bastibe** [comment] 2015-07-24 11:07
This seems to be an issue with org-mode source blocks. This will probably be hard to work around.

Is this an important issue for you? Otherwise, I would add it to the README as a known incompatibility.

**Comment by bastibe** [comment] 2015-09-21 08:06
The incompatibility is now noted in the README

**Closed as completed by bastibe** 2015-09-21 08:06 UTC
