### ISSUE TITLE
Files with no annotations are listed in the annotations file

### ISSUE THREAD

**Issue by mmauger** [bastibe/annotate.el#13] opened 2015-09-18 16:22 UTC
I have annotation-mode enabled in the prog-mode-hook.  As I update packages, the code needs to be read in to be byte compiled and I end up with an entry in the annotations file with that name.  If a file has no annotations it probably ought not appear in the annotations list.

**Comment by bastibe** [comment] 2015-09-19 13:43
Is this a duplicate of #14? How are the two issues related?

**Comment by mmauger** [comment] 2015-09-21 17:26
Not a duplicate and probably not related.

I have a lot of entries in my annotations file that only contain the file name key with no annotations afterwards.  As I open hundreds of files either explicitly or behind the scenes, I end up with a annotations file that is a few K in size listing every file opened but only one file actually has annotations.

**Comment by bastibe** [comment] 2015-09-21 20:59
Oh, now I get it. That should be easy to fix.

**Comment by bastibe** [comment] 2015-09-22 09:41
Should be fixed now.

**Closed as completed by bastibe** 2015-09-22 09:41 UTC
