### ISSUE TITLE
cannot see annotation text

### ISSUE THREAD

**Issue by futurist** [bastibe/annotate.el#34] opened 2017-02-24 09:24 UTC
See my screenshot, is it normal?

![2017-02-24 17 23 35](https://cloud.githubusercontent.com/assets/159167/23297840/119e183a-fab6-11e6-9e62-ac6efe2ca61f.png)

**Comment by bastibe** [comment] 2017-02-24 09:52
This is not normal, no. What major mode and minor modes are you running?

**Comment by futurist** [comment] 2017-02-24 09:59
Please see below:

```
Enabled minor modes: Annotate Anzu Auto-Composition Auto-Compression
Auto-Encryption Blink-Cursor Bug-Reference-Prog Column-Number Company
Company-Flx Cursor-Sensor Delete-Selection Desktop-Save
Diff-Auto-Refine Diff-Hl Editorconfig Electric-Indent Electric-Pair
File-Name-Shadow Font-Lock Form-Feed Global-Anzu Global-Auto-Revert
Global-Company Global-Eldoc Global-Font-Lock Global-Page-Break-Lines
Global-Prettify-Symbols Global-Undo-Tree Global-Whitespace-Cleanup
Goto-Address-Prog Guide-Key Hes Highlight-Symbol Highlight-Symbol-Nav
Ido-Everywhere Ido-Ubiquitous Js2-Refactor Line-Number Mouse-Wheel
Override-Global Paredit-Everywhere Rainbow-Delimiters Recentf
Save-Place Savehist Shell-Dirtrack Show-Paren Tern Tooltip
Transient-Mark Undo-Tree Whitespace-Cleanup Whole-Line-Or-Region
Winner Yas Yas-Global

(Information about these minor modes follows the major mode info.)

JS2 mode defined in ‘js2-mode.el’:
Major mode for editing JavaScript code.

```

**Comment by bastibe** [comment] 2017-02-24 10:16
I can't reproduce your problem on my machine. Does annotate-mode work for other files? I suspect that some minor mode is overwriting or suppressing the display property. Can you try disabling your minor modes one by one (and then possibly reloading the file) to see if any of those is the problem?

**Comment by futurist** [comment] 2017-02-24 10:27
After tried close below modes, (from bottom to top), the annotation appeared.

```
(annotate-mode (quote toggle))
(annotate-mode (quote toggle))
(override-global-mode (quote toggle))
(describe-mode)
(annotate-mode (quote toggle))
(annotate-mode (quote toggle))
(global-eldoc-mode (quote toggle))
(describe-mode)
(annotate-mode (quote toggle))
(annotate-mode (quote toggle))
(highlight-symbol-mode (quote toggle))
(describe-mode)
(switch-to-buffer "*Messages*")
(annotate-mode (quote toggle))
(annotate-mode (quote toggle))
(yas-global-mode (quote toggle))
(describe-mode)
(annotate-mode (quote toggle))
(annotate-mode (quote toggle))
(eldoc-mode (quote toggle))
(annotate-mode (quote toggle))
```

**Comment by futurist** [comment] 2017-02-24 10:29
Also this mode don't support CJK char? I'm tried Chinese, the message is below:

```
Error during redisplay: (jit-lock-function 5491) signaled (args-out-of-range "oijsdofj认说的的这的" 0 20)
```

**Comment by futurist** [comment] 2017-02-24 10:42
Or maybe the problem is the lib itself? I'm tried a new restart, and only annotate on one char (not the whole 3 lines), the annotate appeared. (same minor mode and major mode as above)

![2017-02-24 18 41 38](https://cloud.githubusercontent.com/assets/159167/23300546/eec246e6-fac0-11e6-81fc-9e1a99f8d66e.png)

**Comment by bastibe** [comment] 2017-02-24 12:00
Thank you very much for your analysis.

Unicode used to be a problem, although I thought I fixed those issues. But I can confirm that annotations don't work with the above Chinese string.

I would guess that there is an inconsistency between string handling between `string-width` and `substring` with Unicode strings, which trips up annotate's text layout.

I don't think I have time to look into this in the next few weeks, but I'll see what I can do. In the meantime, if you want to take a stab at this problem, it is most likely to be found in `annotate--annotation-builder` and `annotate-lineate`.

**Comment by bastibe** [comment] 2017-02-24 13:00
OK, I just committed a fix

Can you verify that this fixes your issue?

**Comment by futurist** [comment] 2017-02-24 13:38
Thank you for the quick response!

I've tried the Chinese char work right!

But the whole line annotation cannot show.

![2017-02-24 21 37 02](https://cloud.githubusercontent.com/assets/159167/23305367/6cb402a2-fad9-11e6-8249-9a5cbdea5ffb.png)

**Comment by futurist** [comment] 2017-02-24 13:42
Take it easy! The work around is avoid using whole line annotation... Maybe it's not easy to track on your side... And I will try to fix it when I have spare time maybe...

**Comment by bastibe** [comment] 2017-02-24 15:36
I can't reproduce that one. Can you send me an example file and an example annotation?

**Comment by futurist** [comment] 2017-02-25 01:28
Please see attached

[parse.zip](https://github.com/bastibe/annotate.el/files/800817/parse.zip)

**Comment by bastibe** [comment] 2017-02-27 08:23
OK, this helped. I believe I found and fixed the problem, now. Can you verify that it is indeed fixed?

I also fixed another problem, where annotations were shown at an incorrect column if the line contained tabs. Of course I never found these since I don't use tabs. This was very educational.

**Comment by futurist** [comment] 2017-02-27 09:52
Thank you! it's now worked. But can the annotation position adjusted by user? see the problem:

![2017-02-27 17 48 52](https://cloud.githubusercontent.com/assets/159167/23356588/62d75548-fd15-11e6-864a-777f8e1b2868.png)

Above, you cannot easily distinguish which annotation belongs to which block....

**Comment by bastibe** [comment] 2017-02-27 10:15
The problem is, the annotation includes the final newline, and therefore technically includes the next line. And it always shows up on the last line of the annotation.

I was meaning to provide a setting for customizing the position of the annotation for a while now. It will happen at some point, but it will require some re-architecting of annotate.el and will probably take a while. This would also allow you to put annotations above or below the highlights.

**Closed as completed** 2017-07-04 08:02 UTC
